version: '27.0.3'
services:
  postgres:
    container_name: mc-friends
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: mc-friends
      POSTGRES_PASSWORD: mc-friends
      POSTGRES_DB: mc-friends
    ports:
      - "5432:5432"
  zookeeper:
    image: confluentinc/cp-zookeeper:6.2.0
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    ports:
      - "2181:2181"
  kafka:
    image: confluentinc/cp-kafka:6.2.0
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LOG4J_LOGGERS: ""
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://$DOCKERHOST:9092
      KAFKA_LISTENER_SEQURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_AUTO_CREATE_TOPIC_ENABLE: 'true'
  eureka-server:
    image: eurekaserver:latest
    container_name: eureka-server
    ports:
      - "8888:8888"
    networks:
      - eureka-network
networks:
  eureka-network:
    driver: bridge



