server:
  port: 8090
servlet:
  context-path: /app
spring:
  application:
    name: mc-friends

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
    enabled: true
    drop-first: false

  datasource:
    username: postgres
    password: postgres
    url: jdbc:postgresql://postgres_db/mc_friends
    driver-class-name: org.postgresql.Driver
    dialect: org.hibernate.dialect.PostgreSQLDialect
    hikari:
      connection-init-sql: create schema if not exists account
      connection-timeout: 10000


  jpa:
    generate-ddl: false
    open-in-view: true
    hibernate:
      ddl-auto: none
    show-sql: true

  kafka:
    bootstrap-servers: 79.174.80.200:9092
    kafkaMessageTopic: "registerTopic"
    kafkaMessageGroupId: "Userinfo"

eureka:
  client:
    service-url:
      defaultZone: http://mc-eureka-conteiner:8888/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    hostname: localhost