server:
  port: 8090
servlet:
  context-path: /app
spring:
  application:
    name: mc-friends

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
    enabled: true
    drop-first: false

  datasource:
    username: postgres
    password: postgres
    url: jdbc:postgresql://postgres_db/mc_friends
    driver-class-name: org.postgresql.Driver
    dialect: org.hibernate.dialect.PostgreSQLDialect
    hikari:
      connection-init-sql: create schema if not exists account
      connection-timeout: 10000


  jpa:
    generate-ddl: false
    open-in-view: true
    hibernate:
      ddl-auto: none
    show-sql: true

  kafka:
    bootstrap-servers: 79.174.80.200:9092
    kafkaMessageTopic: "registerTopic"
    kafkaMessageGroupId: "Userinfo"
    kafkaNotificationTopic: "notification-topic"


app:
  jwt:
    secret: "53A73E5F1C4E0A2D3B5F2D784E6A1B423D6F247D1F6E5C3A596D635A75327855"

eureka:
  client:
    service-url:
      defaultZone: http://mc-eureka-conteiner:8888/eureka/
  instance:
    hostname: localhost