Server:
  port:8090
servlet:
  context-path: /app
spring:
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
    enabled: true
    drop-first: false
  datasource:
    username: mc-friends
    password: mc-friends
    url: jdbc:postgresql://localhost:5432/mc-friends?stringtype=unspecified
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
  kafka:
    bootstrap-servers: localhost:9092
app:
  kafka:
    kafkaMessageTopic: "REGISTER_TOP"
    kafkaMessageGroupId: "mc-friends"
  eureka:
    client:
     service-url:
       defaultZone: http://localhost:8888/eureka/
       register-with-eureka: true
       fetch-registry: true